-- 게시판 만들기 
CREATE TABLE CSI_BOARD(
     BNUM	    VARCHAR2(20) PRIMARY KEY 
    ,BSUBJECT	VARCHAR2(50)
    ,BWRITER	VARCHAR2(50)
    ,BCONTENTS	VARCHAR2(2000)
    ,BPW	    VARCHAR2(20)
    ,DELETEYN	VARCHAR2(1)
    ,INSERTDATE	DATE
    ,UPDATEDATE	DATE
);

SHOW USER;
ROLLBACK;

SELECT * FROM TAB;

DROP TABLE HBE_BOARD;
